name: Execute and Save Outputs

on:
  push:
    branches:
      - main

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests matplotlib

    - name: Execute script
      run: python scripts/awf_autoware_build_main_self_hosted.py --github_token ${{ secrets.GH_PAT }}

    - name: Archive output files
      uses: actions/upload-artifact@v2
      with:
        name: output-files
        path: |
          github_action_data.csv
          output_graph.png
    
    - name: Commit and push output files
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<your_email@example.com>" # Replace with your email or a dummy email
        git add github_action_data.csv output_graph.png
        git commit -m "Automated commit: Updated GitHub Action outputs."
        git push
